### ISSUE TITLE
Make a cool README

### ISSUE THREAD

**Issue by torch2424** [jtenner/morp#1]
Because READMEs are cool :smile: :tada: :video_game:

**Comment by jtenner** [comment]
That's what contributors are for. :D

Also I don't have all the details ironed out yet. Not sure what to document.

**Comment by torch2424** [comment]
> That's what contributors are for. :D

😂 🔥 

> Also I don't have all the details ironed out yet. Not sure what to document.

I'd just add the title, License, and motivation. And maybe a blurb about how it is a work in progress 😄

**Comment by torch2424** [comment]
Yay! 😄 👍 🔥 🎉
